name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  meson:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install \
              gobject-introspection \
              libgirepository1.0-dev \
              libglib2.0-dev \
              libgraphviz-dev \
              meson \
              ninja-build \
              valac
      - name: Build
        run: |
          meson setup build
          meson compile -C build
      - name: Test
        run: meson test -C build

  autotools:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get install \
              autoconf-archive \
              gobject-introspection \
              libgirepository1.0-dev \
              libglib2.0-dev \
              libgraphviz-dev \
              valac
      - name: Build
        run: |
          grep -E 'version\s*:\s*\S+-frida' meson.build | cut -d"'" -f2 > .tarball-version
          ./autogen.sh
          make -j$(nproc)
      - name: Test
        run: make check
